### ISSUE TITLE
Registering handlers that handles multiple messages

### ISSUE THREAD

**Issue by alexbrina** [mayuanyang/Mediator.Net#14]
Hi,

I tried to register a command handler that implements multiple ICommandHandlers, then to discover that only the first ICommand was binded to the Handler. I saw your implementation in MediatorBuilder.RegisterHandlers(...) and it explicitly binds just the first interface.

Is that by design? I mean, is there any problem having Handlers with multiple ICommandHandler implementations? And finally, if there's not, do you consider allowing it?

Thanks!

**Comment by mayuanyang** [comment]
Hi Alex

Thanks for getting in touch! That is by design, a command should not have more than one handler, as only one behavior should be triggered , however you can have multiple event handlers for an event. 

Also 2.0 is beta now, it introduce breaking changes, I would suggest to have a look at the new APIs.

I hope that helps. Let me know what you think.

Regards
Eddy

**Comment by alexbrina** [comment]
Ok, that's a little different from what I'm talking, I'm don't have 2+ Handlers for 1 Command, I have a Handler that handles 2+ Commands, something like this:

```
    public class CustomerCommandHandler : ICommandHandler<CreateCustomerCommand>, ICommandHandler<UpdateCustomerCommand>
    {
        public async Task Handle(ReceiveContext<CreateCustomerCommand> context, CancellationToken cancellationToken)
        {
            await context.PublishAsync(new WorkHasBeenDoneEvent());
        }

        public async Task Handle(ReceiveContext<UpdateCustomerCommand> context, CancellationToken cancellationToken)
        {
            await context.PublishAsync(new WorkHasBeenDoneEvent());
        }
    }

```

**Comment by mayuanyang** [comment]
I see what you mean, I don't see any problem of allowing it at the moment, definitely something that I can take a deeper look, PR is also welcome :)

**Comment by mayuanyang** [comment]
I managed to replicate this one, will make the changes soon

**Comment by mayuanyang** [comment]
Hi
 Thanks for getting in touch, will look into it soon.
